name = "nanan"
license = "MIT"
licenselink = "https://github.com/jiusanzhou/hugo-theme-nanan/blob/master/LICENSE"
description = "余生未完-安南说特别定制主题"

homepage = "https://annan.tk"

tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
]

features = [
  "accessibility",
  "algolia",
  "analytics",
  "comments",
  "cover-image",
  "disqus",
  "entry-navigation",
  "favicon",
  "fuse.js",
  "lunr.js",
  "multilingual",
  "multi-author",
  "opengraph",
  "pagination",
  "search",
  "shortcodes",
  "sidebar",
  "single-column",
  "social-menu",
  "staticman",
  "syntax-highlighting",
  "table-of-contents",
  "utterances",
  "widgets"
]

min_version = 0.45

[author]
  name = "周筱鲁"
  homepage = "https://blog.wellwell.work"
