baseURL = "https://annan.tk"
title = "安南说"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "hugo-theme-nanan"

disqusShortname = ""
googleAnalytics = ""

Paginate = 10
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "zh"

[params.info]
title = "安南说"
description = "余生已开始!"
logo = "https://avatars2.githubusercontent.com/u/39580782?s=460&v=4"
title404 = "不能触摸的回忆!"

[params.cover]
image = ''

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["http://localhost:8000/index.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.licence]
name = "知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议"
url = "https://creativecommons.org/licenses/by-nc-sa/4.0/"

[params.copyright]
startYear = "2017"

[params.copyright.holder]
name = "周筱鲁"
url = ""

[params.copyright.from]
name = "好好工作"
url = ""

[params.copyright.base]
name = "杭州"

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#ffcd00"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = ["recent_posts"]
sidebar = ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
codepen = "jiusanzhou"
email = "zoe@wellwell.work"
facebook = "jiusanzhou"
github = "jiusanzhou"
gitlab = "jiusanzhou"
instagram = "jiusanzhou"
linkedin = "jiusanzhou"
twitter = "jiusanzhou"
telegram = "jiusanzhou"

[params.comments]
enable = false

[params.comments.staticman]
enable = true
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2

[params.comments.staticman.github]
username = "MunifTanjim"
repository = "minimo"
branch = "master"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title

[params.comments.utterances.github]
username = "nanshuo"
repository = "nanshuo.github.io"

[params.search]
client = "" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Repo"
weight = -10
identifier = "repository"
url = "https://github.com/jiusanzhou/hugo-theme-nanan"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.zh]
lang = "zh"
languageName = "简体中文"
weight = 1
